name: CI Functions
on:
  push:
    branches: [main]
    paths:
      - functions/**
      - .github/workflows/ci-functions.yml
  pull_request:
    paths:
      - functions/**
      - .github/workflows/ci-functions.yml
jobs:
  ci:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: functions
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Firebase CLI
        run: yarn add firebase-tools

      - name: Install deps and build (with cache)
        run: yarn install

      - name: format
        run: yarn format

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test --ci --coverage --maxWorkers=2
