name: Deploy Functions to Firebase Hosting
on:
  workflow_run:
    workflows: ["CI Functions"]
    types: ["completed"]
    branchs: ["main"]
jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: functions
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: functions
          useLockFile: false
      - name: deploy firebase functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATCHAPP_ED8DD }}
          CONFIG_VALUES: line_config.channel_access_token=${{ secrets.CHANNEL_ACCESS_TOKEN }} line_config.channel_secret=${{ secrets.CHANNEL_SECRET }} openai_config.api_key=${{ secrets.OPENAI_API_KEY }}
