name: Deploy Web to Firebase Hosting
on:
  workflow_run:
    workflows: ["CI Web"]
    types: ["completed"]
    branchs: ["main"]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build && yarn export && ls -a 
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATCHAPP_ED8DD }}'
          channelId: live
          projectId: catchapp-ed8dd
